name: Auto Sync Upstream

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours (UTC)
  workflow_dispatch:

permissions:
  contents: write           # allow push with GITHUB_TOKEN

concurrency:
  group: sync-upstream
  cancel-in-progress: false

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Configure git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote & fetch
        run: |
          git remote add upstream https://github.com/VoltAgent/awesome-claude-code-subagents.git
          git fetch upstream --tags

      - name: Rebase main onto upstream/main
        run: |
          git checkout main
          git rebase upstream/main

      - name: Push updated main (force-with-lease)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main --force-with-lease
          git push origin --tags
